### ISSUE TITLE
Bygningstagging

### ISSUE THREAD

**Issue by gormur** [NKAmapper/building2osm#1]
Ser det står "not used". Mener du at de ekstra taggene du antyder ikke skal bli med i importen? Da bør de kanskje rett og slett ikke nevnes i det heletatt? Samtidig ser jeg behov for ekstra tagger.

Noen kommentarer til konkrete bygningstyper:j

141 kan godt få building_levels=2
142 kan godt få "building_levels=3 or 4" etc.

193 "brakker" er ikke helt det samme som "barracks" på engelsk. "Barracks" har mer permanent karakter. "Demountable" buildings er mer som norske "brakker".

Ikke alle 673 er kristne. Disse knapt et "place_of_worship" heller. Og "worship_of_god" er vel ikke en tagg i det heletatt?
674 er ikke bare muslimske moskeer, noen er også synagoger. Tror ikke det blir populært å blande dem. Ekstra-taggene bør slettes eller byttes med noe a-la "fixme=mosque or synagogue?"

840 kan også få amenity=toilets
970 kan også få emergency=yes

**Comment by NKAmapper** [comment]
Takk for kommentarer, veldig nyttig. Se nedenfor.

> Ser det står "not used". Mener du at de ekstra taggene du antyder ikke skal bli med i importen? Da bør de kanskje rett og slett ikke nevnes i det heletatt? Samtidig ser jeg behov for ekstra tagger.

I denne versjonen er det kun building=\* som blir tagget, ingen amenity=\*, leisure=\* osv. Tanken var å utvide senere med flere tagging-forslag fra denne kolonnen, men er litt tvilende til om kvaliteten er god nok. Tar kolonnen bort senere om den ikke kan brukes. 

> 141 kan godt få building_levels=2
> 142 kan godt få "building_levels=3 or 4" etc.

Det var jo en interessant ide. Men når jeg sjekker mot f.eks. filen for Trondheim, så viser det seg at #141 har både 2, 3 og 4 etasjer, og #142 har 2-7 etasjer. Så akkurat denne gruppen bygningstyper er nok ikke brukt så konsekvent.
 
> 193 "brakker" er ikke helt det samme som "barracks" på engelsk. "Barracks" har mer permanent karakter. "Demountable" buildings er mer som norske "brakker".

Denne lurte jeg også. #193 er brukt om boligrigger for anlegg osv. building=demountable er lite brukt og ikke dokumentert i wiki. Hva med building=container? ([Wikipedia](https://de.wikipedia.org/wiki/Containergebäude))

> Ikke alle 673 er kristne. Disse knapt et "place_of_worship" heller. Og "worship_of_god" er vel ikke en tagg i det heletatt?
> 674 er ikke bare muslimske moskeer, noen er også synagoger. Tror ikke det blir populært å blande dem. Ekstra-taggene bør slettes eller byttes med noe a-la "fixme=mosque or synagogue?"

Enig, men ønsker som sagt bare å bruke building=*.
