### ISSUE TITLE
Polygonproblemer

### ISSUE THREAD

**Issue by NKAmapper** [NKAmapper/building2osm#12]
Split feiler for Utsira (melding om at polygon ikke henger sammen), selv om koordinat for første og siste node ser like ut.

Polygon med inner ser heller ikke ut til å fungere, f.eks. valgkretser i Ås og i Nordkapp. Om indre polygon ikke støttes så ville det være greit om ytre polygon likevel støttes.

Tar du en titt på dette, @noenandre ?

WMS endpoint for kretsene: http://openwms.statkart.no/skwms1/wms.matrikkel.seeiendom2

**Comment by noenandre** [comment]
Hull i polygoner støttes, det! Hvis det ikke hadde falt ut en linje med kode fra gml_patch_assembler. PR kommer.
Utsira feiler ikke hos meg, jeg kan ikke gjenskape den feilen.

**Comment by NKAmapper** [comment]
Er split avhengig pattern matching i Python 3.10? Den har jeg ikke.

**Comment by noenandre** [comment]
Nei, skriptet er Python 3.8 kompatibelt. Du tenker på de to stedene jeg har kommentert at koden kunne dratt nytte pattern matching? Tenker vi fjerner de kommentarene nå.

**Comment by noenandre** [comment]
Falt ut, som i at du fjernet kodelinja `pos_list = gml_inner.find(".//gml:posList", namespace)` fra gml_patch_assembler i går, av en eller annen grunn.

**Comment by NKAmapper** [comment]
Rotet rundt der ja, så fikk ikke lagt alt tilbake ser det ut til. Utsira fungerer nå, kanskje en følgefeil i går.
