### ISSUE TITLE
Eksklave mangler bygninger

### ISSUE THREAD

**Issue by NKAmapper** [NKAmapper/building2osm#14]
Municipality_split.py får ikke med bygningene i Tønsbergs eksklave ved Undrumsdal (testet med valgkrets-split). Valgkretsen Undrumsdal har her to polygoner. Gjelder også valgkrets nr 10 "Tønsberg", som består av to polygoner.

**Comment by noenandre** [comment]
Så istedenfor å liste opp Undrumsdal én gang med to polygon-patcher, så er den listet opp to ganger?
Da må det skrives mer enn et par linjer kode for å slå dem sammen igjen.

**Comment by NKAmapper** [comment]
De vises som to separate ways når valgkretser-filen lastes inn.
