### ISSUE TITLE
Splitte import i bydelsfiler

### ISSUE THREAD

**Issue by NKAmapper** [NKAmapper/building2osm#4]
Siden importfilene vil bli oppdatert fremover ville det være praktisk å ha et lite skript som lager bydelsfiler for de fire store byene.

- Bydelsgrensene kan hentes fra OSM.
- Geojson format.
- Gjenbruke f.eks. _inside_polygon_ fra building2osm.
- Filnavn f.eks. med endelse _\_bydel\_\<navn>\.geojson_.
- Helst ikke eksterne avhengigheter.

@noenandre - Noe for deg?

**Comment by noenandre** [comment]
Jeg har startet, men er nok ikke like raks til å kode som deg.
Jobber med å få konvertert de administrative relasjonene til polygoner.

**Comment by NKAmapper** [comment]
Ja de grenserelasjonene er et pirk. Retning må snus så den blir konsistent, rekkefølgen på medlemmene kan være feil osv osv. Samme type jobb som i nvdb2osm når segmentene skal settes sammen til lengre veier.
Bra med en liten dugnad på dette :)

**Comment by NKAmapper** [comment]
Bare for å legge linken et sted til senere:
Her er grensene for valgkretser: [link wfs](https://kartkatalog.geonorge.no/metadata/valgkretser-wfs/d76220cd-a25c-4eca-9229-cd5099f6ddaf).
Gir færre/større deler per kommune enn postdistriktene.

**Comment by NKAmapper** [comment]
Mer info om valgkretsene:

URL: https://wfs.geonorge.no/skwms1/wfs.valgkretser?VERSION=2.0.0&SERVICE=WFS&SRSName=EPSG:4326&REQUEST=GetFeature&TYPENAME=Valgkrets&Filter=

Filter:
```xml
<Filter> 
	<PropertyIsEqualTo> 
		<ValueReference xmlns:app="http://skjema.geonorge.no/SOSI/produktspesifikasjon/Valgkretser/20190520">
			app:nyttkommunenummer
		</ValueReference> 
		<Literal>
			{municipality_id}
		</Literal> 
	</PropertyIsEqualTo> 
</Filter>
```

Valgkretser med flere "exterior" polygoner (f.eks. eksklaver) er lagt ut som flere separate polygoner. Enklaver er "interior" polygoner.

Nåværende oppdeling ble laget til valget 2019, som skulle følge kommunegrensene f.o.m. 1.1.2020. Det har vært noen få grensejusteringer etter dette som ikke er med.

**Comment by NKAmapper** [comment]
Det viser seg at postnummer-distriktene ikke alltid følger kommunegrensene, så det skaper noen utfordringer med bygninger som blir til overs ...
F.eks. vest i Kristiansand.

**Comment by noenandre** [comment]
Vi kan bruke WFS-tjeneren for postnummer istedenfor FTP-serveren, og istedenfor å filtrere etter kommune, slik du foreslår for valgkretsene kan vi be om alle postnummer som er innenfor en avgrensingsboks for alle bygninger i fila som er lastet inn?

**Comment by NKAmapper** [comment]
Det ville nok fungere, @noenandre (men har ikke sett på WFS'en). Alternativt kunne vi bare lagre alle bygninger som blir "til overs" (ikke er med i noe postnummer-distrikt i kommunefilen) i en egen fil til slutt.

Men om du har lyst til å lage en variant for valgdistrikter, så tror jeg det vil være mer verdiøkende. Jeg gjorde importen i Kristiansand etter postnummer, og det fungerer jo, og er nødvendig å dele opp for å få importert en stor kommune, men det blir altfor mange postdistrikter. Det er ok i landkommuner, men blir for mange i bykommunene. Valgdistriktene har færre områder per kommune. Ser ellers ut til at det vil være mye gjenbruk av kode.

WMS for de ulike oppdelingene (endpoint): https://openwms.statkart.no/skwms1/wms.matrikkel.seeiendom2?request=GetCapabilities&Service=WMS

**Comment by NKAmapper** [comment]
Thank you !

Feel free to have look at "valgkretser" (electoral districts), also described in #4 :) They would produce fewer files than postal codes, which is more convenient for the larger municipalities.

**Comment by NKAmapper** [comment]
Opsjon for valgkretser (egentlig stemmekretser) er lagt til nå.
